version: '3.8'
services:

  cassandra:
    image: cassandra:latest
    container_name: cassandra-vector
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=VectorCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 10s
      timeout: 5s
      retries: 10
