spring:
  application:
    name: observability

  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
    chat:
      observations:
        include-error-logging: true
        log-completion: true
#        log-prompt: true # it is shows default system prompt also if chat gpt does not have access to external resource

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0